apiVersion: v1
kind: Service
metadata:
  name: {{ include "template.fullname" . }}
  namespace: {{ include "template.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  labels:
    {{- include "template.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- range .Values.service.additionalPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "template.selectorLabels" . | nindent 4 }} 